name: Publish on NPM

on:
  release:
    types: [published]

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
            version: 8

        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 16.x
            cache: "pnpm"
            registry-url: 'https://registry.npmjs.org'

        - name: Start build
          run: |
            pnpm install --frozen-lockfile
            pnpm run lint
            pnpm run build

        - name: Publish to npm
          run: pnpm publish --access public --git-checks=false
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

